# Base image. Specifying the version is crucial! It's very important to specify the version of Node.js.
FROM node:18.16.0-alpine

#Install serve package
RUN npm i -g serve

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json
COPY ./package.json /app/package.json
COPY ./package-lock.json /app/package-lock.json

# install project dependencies
RUN npm install
RUN npm install @vue/cli -g

# Copy the project files
COPY . /app
COPY ./frontendDockerEnvFiles/.env .

# Build the project
RUN npm run build

# Expose a port
EXPOSE 8083

# Executables
CMD [ "serve", "-s", "dist", "-l", "8083" ]
# CMD [ "npm", "run", "serve", "--", "--port", "8083" ]