# Base python package
FROM python:3.9-slim-buster

# Working directory
WORKDIR /app

# Copy the dependencies
COPY requirements.txt ./

RUN pip3 install -r requirements.txt

COPY . .
COPY ./backendDockerEnvFiles/.env .
COPY ./backendDockerEnvFiles/.flaskenv .

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]


